### ISSUE TITLE
Flex Message表示内容について

### ISSUE THREAD

**Issue by miso-develop** [mochan-tk/clova-handson-201906#4]
今更ながらで申し訳ないのですが、ソース見て気付きましたがカールセルの横方向にのせる情報がひとつの旅行情報の各種情報リンクになっていると思いますが、ここ別プランを表示してってもいいですか？

その場合LIFF側にトップページを置くか、ひとつのボックス内に各種情報へのリンクボタンつけまくるか、になると思います。

**Comment by mochan-tk** [comment]
もちろんOKです！現状のプログラムもカルーセルのサンプルの意味合いで書いてるだけだったりします。
（現状のプログラムは大きな流れ以外の詳細な部分は変更してあるべき姿に変えていただけますと(　´∀｀)bｸﾞｯ!）

**Comment by miso-develop** [comment]
オッケー牧場！
